import { createSlice, PayloadAction } from '@reduxjs/toolkit'


const initialState = {
    opticianlist:[
      {idO:Math.random(10000),
        imageO:"https://www.bonnes-adresses.tn/public/images/couverture/opticiens.jpeg",
       nomO:"BEN ZID OPTIC",
        descriptionO:"OpticAymen Ben Zid",
      gsmO:"22806114",
      faxO:"36193837",
      telphp:"36193837",
      AdresseO:" Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:" https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"aymenbenzid@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://protectglobal.tn/wp-content/uploads/sites/79/2019/01/Optiker-600x450.jpg",
       nomO:"Wassim Abid Opticals",
      descriptionO:"Wassim Abid",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.opticiens-atol.com/media/amasty/amlocator//A/T/ATOL-LES-OPTICIENS-52-RUE-SADI-CARNOT-76160-DARNETAL_1.jpg",
       nomO:"B-Optique",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://cap.marche.be//media/etalage-corinne1.jpg",
       nomO:"OPTIQUE B. RAFAA",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.bigdeal.tn/media/cache/sliddetaildeal/medias/12_2016/Tanit_Optic/B3.png",
       nomO:"Bagdadi Optic",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.pagesjaunes.fr/media/agc/7e/cf/4e/00/00/21/91/ef/b9/1e/5d397ecf4e00002191efb91e/5d397ecf4e00002191efb91f.jpg",
       nomO:"Narjes Optic",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.bonnes-adresses.tn/public/etablissements/5c6e7a422e5f7.jpg",
       nomO:"Abdelkafi Opticals",
      descriptionO:"Abdelkafi",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCdGDZKoQBc7M_lsplOyqwYVCGtmD_uVzHolZJDrNEf_Czmdrmn8uWgybjOdJMg4ix2Bo&usqp=CAU",
       nomO:"tal optical",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.monopticien.com/data/shops/615_photo@5A8C0164-OPTIC-LY.JPG",
       nomO:"autre vue",
      descriptionO:"autre vue",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKPXOd-HDstQhEMnc2dM__jMINcAu3yUygmMOMfkeQS9OK_uoiYjZ8Jn34YLOQpnNKPss&usqp=CAU",
       nomO:"lunicol",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://krys-visionplus-storage.omn.proximis.com/Imagestorage/imagesSynchro/0/0/6ee3d39870d9eb2fa7b9bf54def2186a105c711b_shop_145_image_3.jpeg",
       nomO:"Vision Plus",
      descriptionO:"Wassim Abid",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.expertsantevisuelle.com/images/Default/slider/slider-2.jpg",
       nomO:"OPTICIEN DD",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://opticdesign.fr/wp-content/uploads/2019/05/renover-boutique-doptique.jpg",
       nomO:"HOP OPTIC",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"http://www.marieauthouartcreation.fr/wp-content/uploads/2014/10/DSCF0588-copie1.jpg",
       nomO:"LANCHON",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"http://padedesign.com/wp-content/uploads/2017/09/padedesign-vitrine-opticien-colliaux-atelier-5.jpg",
       nomO:"COLAUX",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2Agii4cKRWtMAxNlbNYHVMAWeZjw7p1L5rXyJCvaEfAmTgrg0VrEiuhe8a4-BffJ-Y8w&usqp=CAU",
       nomO:"HEM optique",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://i.skyrock.net/8532/43258532/pics/1741621862_small.jpg",
       nomO:"opticien",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://remeng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2020/03/30/node_142413/11596445/public/2020/03/30/B9723081829Z.1_20200330152535_000%2BG1UFQ65K0.1-0.jpg?itok=zEqT8pCp1585591975",
       nomO:"Ludo Optique",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://commerce-ploermel.com/wp-content/uploads/2016/07/prevoteau-opticien-1-1024x683.jpg",
       nomO:"CENTRE Optiique",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://lh3.googleusercontent.com/proxy/WafDcfEF0iVWpOnmvIdleersV9qY4m9hk8L2ED4YVZZ25SG5u1_6rE1Fwn4brFOdnvZcvu4n7Q5vwDbVwUZfwnuxBQWKxNN3kUMG1UmSe6HMD6IznZlvBVYNghZt4co0-K8qXv3-iyF_JTLTTWfs",
       nomO:"ADGARD",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.conceptsign.fr/wp-content/uploads/2018/06/direct-optique-paris-2.jpg",
       nomO:"direct Optic",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://batsign.fr/images/enseigne-lettres-aluminium-laque-ral-opticien-paris2.jpg",
       nomO:"Optical concept",
      descriptionO:"Wassim Abid",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://pbs.twimg.com/media/Da9ufRnW4AAmyOl.jpg",
       nomO:"vue claire",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.monopticien.com/data/shops/2347_photo@5F903627-ESPACE-OPTIQUE-BLOIS.jpg",
       nomO:"espace optique",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.apointcom.fr/wp-content/uploads/2011/09/fabrication-enseigne-lumineuse-opticien-a-vincennes-94300-autrement-vue.jpg",
       nomO:"AUTREMENT VUE",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://d1nuj3f2uuhf3u.cloudfront.net/attached_pos_photos/345104/landing_page.jpg?1619449564",
       nomO:"COPTICAL",
      descriptionO:"Wassim Abid",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.langlois-opticiens.com/assets/img/p1/2_about_img.jpg?t=1556273159",
       nomO:"LANGLOIS",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://optikid.fr/public/files/image/2762/Facade%20Bono%20Opticiens%20.jpeg",
       nomO:"Bono",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://lh3.googleusercontent.com/proxy/DuJh7D3n7RNSTUc7mIJkyv1TKaYfnmUGjthj_3iP2Up40yUJHiPNQNtKPPFYz1U4B8lRueen1_ijPuWAhBOBAm9X281haoYZPvtO2oKsLxTQNlJ7L2RNjsPAZiOTDS62YZ1OzHE6nTYq6TmRYiJQRQSwR89O0Juhpeqmap4WDtX1mSc",
       nomO:"Balouzat",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://i.pinimg.com/236x/04/a4/b7/04a4b7108c41106580b890bf7ed93827.jpg",
       nomO:"CLAIRR VISION",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQahCzulCYX84MvmOr_ila84bRE715lZtO_MA&usqp=CAU",
       nomO:"AA Opticien",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIarPk_kKUNjzEOpGobuEYOOTeDUcB0XeXpFcYPtKuTurBIkGXz_rR40fdoC5H-4eXpBM&usqp=CAU"
        ,
       nomO:"Balti",
      descriptionO:"balti",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.focusoptique.tn/wp-content/uploads/2021/04/opticien-recrute-356x220.gif",
       nomO:"Opticien",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://fastly.4sqi.net/img/general/600x600/67210120_pChL2N0vhBm2mu2_fCOGDfXXRLEmsTx_h0B5tYuUXu8.jpg",
       nomO:"Tarrouche Optic",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://i.pinimg.com/originals/00/15/75/001575cc87dc688481112bea6f360046.jpg",
       nomO:"Andersen Opticians",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZvtU8bl1rqrydMktvEiEjRyqJiK_ThV3Wnb6BAtUvVDWsss7__l3yjUc3rYVW28xHqpk&usqp=CAU",
       nomO:"EGG",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.med.tn/uploads/offices/187207_1556291511_5cc31fb73fd4e.jpeg",
       nomO:"Corall Optic",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://d1nuj3f2uuhf3u.cloudfront.net/attached_pos_photos/360679/landing_page.jpg?1543243658",
       nomO:" Optical Center",
      descriptionO:"Wassim Abid",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.monopticien.com/data/shops/2859_photo@5C643961-REGARD-DE-LEVIS.jpg",
       nomO:"Optique",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://enseigne.tn/wp-content/uploads/2019/02/facade-boutique-tunis.jpg",
       nomO:"Gautier",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.moncoeurducommerce-smvi.fr/wp-content/uploads/2020/04/La-boite-%C3%A0-lunettes-Opticien-vitrine.jpg",
       nomO:"Lunettes",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"http://unautreregardopticien.fr/wp-content/uploads/2020/12/127118403_4658421717566515_6555030198855074847_n.jpg",
       nomO:"un autre regard",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPmeta44lpV90UCjakwyNJxSU3LUszXtTNmBZt41CUuX6Bdv1OK0tMdV1QP_Ml7R4CKvU&usqp=CAU",
       nomO:"Wassim Abid Opticals",
      descriptionO:"Clair ootique",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://lh3.googleusercontent.com/proxy/o6Lx2FIb_CLffPTi_kMQ0QD7IPRgzUDhxKWzeaZcfObfS9IU5Rgz9u8l17qUgXNLeVNtwiWjcDDAoo3Ip1StFzEMhLmX-Il72DoVIxRWD-O1120VXMqyNX-vey69PYB8H7A4K_EHAw",
       nomO:"lunette Optique",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpOeMIxcCyautb6f27vkL99pTPKN-3z8JAyg&usqp=CAU",
       nomO:"OPTIQUE wael",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://i.pinimg.com/originals/41/c5/05/41c5059079b117b9990e68850efb5f47.jpg",
       nomO:"Vision Optic",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.lenseigne.com/public/img/big/received651362795594770jpeg_5f6b437742a09.jpeg",
       nomO:"L'opticien",
      descriptionO:"Wassim Abid",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.toute-la-franchise.com/images/zoom/generale-optique-france-grandvision-franchise.jpg",
       nomO:"Green Optique",
      descriptionO:"",
      gsmO:"93 879 948",
      faxO:"75 277 208",
      telphp:"75 277 208",
      AdresseO:"Avenue Jilani Lahbib (Sidi Marzouk) En face ISG 6091 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"b.optique3@gmail.com",
    },{idO:Math.random(10000),
        imageO:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPmeta44lpV90UCjakwyNJxSU3LUszXtTNmBZt41CUuX6Bdv1OK0tMdV1QP_Ml7R4CKvU&usqp=CAU",
       nomO:"Clairoptique",
      descriptionO:"Fatma Rafaa",
      gsmO:"22638666 ",
      faxO:"75277926 ",
      telphp:"75277926 ",
      AdresseO:"157 AV. Mohamed Ali - 6001 GABES",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.monopticien.com/data/shops/610_photo@5EFDB6A9-Optique-D-Orves.jpg",
       nomO:"Optic d'orves",
      descriptionO:"Anis Abdelatif",
      gsmO:"",
      faxO:"75 270 886",
      telphp:"75 270 886",
      AdresseO:"19 Rue,  9 Avril 6000 Gabes",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://www.pagesjaunes.fr/media/ugc/roosevelt_optic_07505600_192012030",
       nomO:"Rooselvet optic",
      descriptionO:"Narjes",
      gsmO:"",
      faxO:"75 277 236",
      telphp:"75 277 236",
      AdresseO:"Adresse : Av. Farhat Hachad - شارع فرحات حشاد, Gabès",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },{idO:Math.random(10000),
        imageO:"https://en.cap3000.com/-/media/cap3000/images/enseignes/photos/visuel-presentation-771-579.jpg",
       nomO:"Opticien",
      descriptionO:"Wassim Abid",
      gsmO:"",
      faxO:"75 277 220",
      telphp:"75 277 220",
      AdresseO:"immeuble dar tabib Gabès, 6000",
      siteO:"https://www.allo-docteur.com.tn/fr/gabes/5117-para-medicales/opticiens/gabes.html",
      emailO:"",
    },
  ]
}

export const OpticianSlice = createSlice({
  name: 'opticianlist',
  initialState,
  reducers: {
    AddTodoPD: (state, action) => {
      state.opticianlist.push(action.payload)
    },
    DeleteTodoPD:(state,action)=>{
      state.opticianlist=state.opticianlist.filter(el=>el.idO!==action.payload.idO)
    },
    DoneTodoPD:(state,action)=>{
      let i =state.opticianlist.findIndex(el=>el.idO==action.payload.idPO)
      state.opticianlist[i]={...state.opticianlist[i], isDone:!state.opticianlist[i].secteurO}
     
    },
    EditTodoPD:(state,action)=>{
      let i =state.hospitallist.findIndex(el=>el.idO==action.payload.idO)
      state.opticianlist[i]={...state.opticianlist[i], descriptionO:action.payload.secteurO}
    }
  },
})

// Action creators are generated for each case reducer function
export const {AddTodoO,DeleteTodoO, DoneTodoO,EditTodoO} = OpticianSlice.actions

export default OpticianSlice.reducer